export const SaveFields = {
  name: 'name',
  tags: 'tags',
  descriptionShort: 'descriptionShort',
  descriptionMarkdown: 'descriptionMarkdown',
  tests: 'tests',
  testName: 'testName',
  testInput: 'testInput',
  testExcepted: 'testExcepted',
  validatorInput: 'validatorInput',
  validatorExcepted: 'validatorExcepted',
  stubGenerator: 'stubGenerator',
  stubLanguage: 'stubLanguage',
  solutionLanguage: 'solutionLanguage',
  solutionIsValid: 'solutionIsValid',
};
